.PHONY: clean All

All:
	@echo "----------Building project:[ CEOS - Debug ]----------"
	@cd "CEOS" && "$(MAKE)" -f  "CEOS.mk"
clean:
	@echo "----------Cleaning project:[ CEOS - Debug ]----------"
	@cd "CEOS" && "$(MAKE)" -f  "CEOS.mk" clean
